"""schema iniziale

Revision ID: 7fb89fa744de
Revises: 
Create Date: 2026-09-12 09:40:05.891638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb89fa744de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estrazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ruota', sa.Enum('BA', 'CA', 'FI', 'GE', 'MI', 'NA', 'PA', 'RM', 'TO', 'VE', 'RN', name='ruota'), nullable=False),
    sa.Column('numeri', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'ruota', name='uq_estrazione_data_ruota')
    )
    op.create_index('ix_estrazione_data', 'estrazione', ['data'], unique=False)
    op.create_table('previsione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('LOTTOFACILE1', 'LOTTOFACILE4', 'LOTTOFACILE5', 'FULMINE', 'UN_SOLO_AMBO_SECCO', 'AMBO_SECCO_CAOTICO', name='metodo'), nullable=False),
    sa.Column('data_rilevamento', sa.Date(), nullable=False),
    sa.Column('ruote', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('colpi', sa.SmallInteger(), nullable=False),
    sa.Column('anche_tutte', sa.Boolean(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('avviso', sa.Text(), nullable=True),
    sa.Column('creata_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_previsione_data_metodo', 'previsione', ['data_rilevamento', 'metodo'], unique=False)
    op.create_table('sorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previsione_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('AMBATA', 'AMBO', 'TERZINA', 'QUARTINA', name='tipo_sorte'), nullable=False),
    sa.Column('numeri', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('stato', sa.Enum('APERTA', 'VINTA', 'SCADUTA', name='stato_sorte'), nullable=False),
    sa.Column('colpi_valutati', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['previsione_id'], ['previsione.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sorte_previsione_id'), 'sorte', ['previsione_id'], unique=False)
    op.create_index('ix_sorte_stato', 'sorte', ['stato'], unique=False)
    op.create_table('esito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sorte_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ruota', sa.Enum('BA', 'CA', 'FI', 'GE', 'MI', 'NA', 'PA', 'RM', 'TO', 'VE', 'RN', name='ruota'), nullable=False),
    sa.Column('colpo', sa.SmallInteger(), nullable=False),
    sa.Column('numeri_usciti', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('a_tutte', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sorte_id'], ['sorte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sorte_id', 'data', 'ruota', name='uq_esito_sorte_data_ruota')
    )
    op.create_index(op.f('ix_esito_sorte_id'), 'esito', ['sorte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esito_sorte_id'), table_name='esito')
    op.drop_table('esito')
    op.drop_index('ix_sorte_stato', table_name='sorte')
    op.drop_index(op.f('ix_sorte_previsione_id'), table_name='sorte')
    op.drop_table('sorte')
    op.drop_index('ix_previsione_data_metodo', table_name='previsione')
    op.drop_table('previsione')
    op.drop_index('ix_estrazione_data', table_name='estrazione')
    op.drop_table('estrazione')
    # ### end Alembic commands ###
